language: node_js
node_js:
- '6'
sudo: false
deploy:
  provider: npm
  email: trustmaster@kodigy.com
  api_key:
    secure: iWL+vHziNaJxfoHTg7r2egmzdOKpbNyhToXwujbE2QM+iHKRTRpJbpchUAX72Ys5AoaGo8kVs+h6AlOAe8ciWgQJBgzZ4+au7yF7LWNk9x5/NVRXkj36nPV5JUvRpb3Mgax87c9br5Lz8C1bcC3xFebG+47squ7WlnKt+cWedblyh0wsaz9a/3HJX6GP/f/oeqPYv2/CD+3KMYUK8aTWPaLVbRUo+2miat8K4Bwe3BxYEnh7LQyCGpm2+lussfqmjK3jOxk88B9vXYXYc2P536o4NNYogFU8w/hkvxxUqyMIzb2Nr/QZzx0bN17X+L+8Ma6lVjnYbwsaK4UDZoog55x8kYPG4ce0RJVwisFahs6q0aD3/4YQrmjmmii0C3gvUGug2Rx5QXG1D7Ngv7HsQGq9eFdP1y3LsMelws5PIV2bO/szQ34XL0wjZaaRieWskOyg7avT9KehdUJ5bOEVBRBG1s2ji4wxkpy+8gx6ccP6Jx/ZSKIJSO9fQ0DOMR1H5zfFBqQjVohXkRLNbKrTvPlWaK4F9VFXhy5RPNOh9eJYXgCdENXAV+Da6UyRZJd/TsaUvo55cF16g77tki/rzXAWQR6mLWUkE6JpjPFKgN6m8aH+XvirKz+DG0pGhAGTd4OL4NqBovfNZOKpGn6EqblyS1x/MOiJJKxGKUGbeM0=
  on:
    tags: true
    repo: noflo/noflo-wrapper
