language: node_js
node_js:
- lts/*
sudo: false
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: hJoYMbxBD26PGD6d5Ar7PGE0CtXFp/wWia2QNpubh44wV/XuGtsN5s9tcllxsofEKd+ZuQqNSqmiy8TGZjeXy63zWBfg8KgOEbIpfyqHJ2p91oCiIAq5sKqwFAMqii1najhqoXUnjTxXTU+nql0qn5/49P5T9/fmGS2V9/4qkTguYVjpH3j0/V6E0sFJdlSGn2U49knjNFlbxro55cY4VezPNAeBqmL3DKOzXo3Dv5d5BcdrKLG4egjLoPXZjQ8XVsSb4WanCT+12LUrbSPLOBcxn5M6L+NwtGWs/P1JDX7Q1zEDkRRWqaktGCERJ1YWwaJkY3P+jWxcAKPAfbf0HUx/2pk9DRlGmtJkpz/oXRgzeCCmIe7f/Zej3a6Woj2H7RAEkeA7RHrfksD1uNecnTiWptkjL6Dkobk8snDaXhuAgwk4hm2CRk7htGyKPpBqMTsRiPDUA72iRVUXHrVVVIDOJRSF5G87JNI4wy3q7Cw8RGxzr8SRw7VmKpWOqlsJ/6jjsukWYNz+COPa6wGSHoVZl+gAWiq7RlqpXJ6f/NOg7fFM4FafwT7Bd6WpjFOGqZwSe8ACzcLcUEamWKV/oeK0VOaVkoTxkoxt5N57av4Lzv5tG0P5y3bUJssHNrT69cWamb23l3paZPs3HYWYrJxPIA1v7c4/ZZsF5GGIVcY=
  on:
    tags: true
    repo: noflo/noflo-wrapper
